development:
  adapter: postgresql
  database: snapplicator_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: snapplicator_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: snapplicator_production
  pool: 5
  timeout: 5000